[project]
name = "projeto-aws-bedrock-with-knowledge-base"
version = "0.1.0"
description = "Aqui usaremos bedrock da AWS e uma base de conhecimento"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
]
